### PR TITLE
Drop Python 3.6 in `typing_extensions`

### PR DESCRIPTION
**Pull request by AA-Turner**
Python 3.6 is now end of life (https://github.com/python/peps/commit/58b93bdfdb57a1ec3641983c6738341c5072d5b4)

This drops support and does various cleanup things (see commits for more detail).

Hopefully this would make e.g. #963 easier (xref https://github.com/python/typing/pull/963#issuecomment-983242050)

A

### CODE REVIEW

**Comment by srittau** [comment]
+1 from me, but I know some people are in favor of supporting 3.6 for a while longer. On the other hand, typing-extensions 4 is still available.

**Comment by hauntsaninja** [comment]
Is PEP 646 the only thing that will be included in the short-term future? If so, +1 from me. If not, might be nice to get those in, although as srittau says, we could always backport (but that's a hassle).

**Comment by JelleZijlstra** [comment]
The only other thing that is on the horizon right now is `dataclass_transform` I believe. (There are also pending PEPs for `Literal[str]` and callable syntax, but those shouldn't affect typing-extensions. We already support `Self`.) But `dataclass_transform` will mostly be a stub-only thing, so it doesn't seem too important to support at runtime in typing-extensions.

**Comment by srittau** [comment]
A minor wish: Could we split the changes to the workflow file (except for dropping 3.6) out into a separate PR for a cleaner history?

**Comment by AA-Turner** [comment]
Only dropping 3.6 remains in this PR, see #1017 

A

**Comment by JelleZijlstra** [comment]
I'd like to do one more release (4.1.0) with 3.6 support for the PEP 646 objects. After that we can drop 3.6. It should not require a major version change though, it can just be 4.2.0.

**Comment by AA-Turner** [comment]
Updated the version number to 4.2.0 -- I can merge in master now to resolve conflicts, or wait until PEP 646 support &c has been released in v4.1.0. Which would you prefer?

A

**Comment by JelleZijlstra** [comment]
Thanks! I'd suggest to defer dealing with the merge conflicts until we're ready, because you'll just get new ones if there are any additional changes.

**Comment by srittau** [comment]
Converted to draft to signal that we are "waiting for stuff". Please unconvert once 4.1.0 has been released.

**Comment by srittau** [comment]
Superceded  by #1104. Thanks!

**Pull request closed without merging**
