### PR TITLE
Made proposed change to the typing spec with regard to `NoReturn` and…

### PR DESCRIPTION
**Pull request by erictraut**
… where it can be used.

### CODE REVIEW

**Review by sobolevn — APPROVED** [review]
I agree, I have many existing use-cases for `NoReturn` in different contexts. I think that making it not-the-same-as `Never` is aсtually an unneeded complexity.

**Review by gvanrossum — APPROVED** [review]

**Review by JelleZijlstra — APPROVED** [review]

**Review by rchen152 — APPROVED** [review]

**Review by hauntsaninja — APPROVED** [review]
Thanks! The phrasing might be read as implying some sort of stylistic preference, curious if that was intentional

**Comment by erictraut** [comment]
> The phrasing might be read as implying some sort of stylistic preference, curious if that was intentional

Not really. The intention was to try to give some background explanation for why there are two ways to spell the same type — and where each has typically been used. If you have a suggestion for how to improve the wording, let me know.

**Comment by JelleZijlstra** [comment]
Merged as this has been approved by all Council members. I think the wording is fine, but we can tweak it in a follow-up PR if desired.

**Pull request merged**
